name: Staging deployment

on:
  push:
    branches:
      - dev
      - feat/backend

jobs:
  build:
    runs-on: [self-hosted, stage-env]
    steps:
      - uses: actions/checkout@v3
        with:
          path: "./stage-deploy"
      - run: echo ${{ secrets.APP_STAGE_ENV }} | base64 --decode > apps/app/.env
        working-directory: "./stage-deploy"
      - run: docker build -t docker.flows.sh/app-frontend-stage:${{github.sha}} -f infrastructure/docker/next.Dockerfile --build-arg APP=app .
        working-directory: "./stage-deploy"
      - run: docker build -t docker.flows.sh/web-frontend-stage:${{github.sha}} -f infrastructure/docker/next.Dockerfile --build-arg APP=web .
        working-directory: "./stage-deploy"
      - run: docker build -t docker.flows.sh/docs-frontend-stage:${{github.sha}} -f infrastructure/docker/next.Dockerfile --build-arg APP=docs .
        working-directory: "./stage-deploy"
      - run: docker build -t docker.flows.sh/backend-stage:${{github.sha}} -f infrastructure/docker/nest.Dockerfile .
        working-directory: "./stage-deploy"

  deploy:
    needs: [build]
    runs-on: [self-hosted, stage-env]
    steps:
      - run: docker stop flows-app-frontend-stage
      - run: docker rm flows-app-frontend-stage
      - run: docker run -d --restart always -p 6001:3000 --name flows-app-frontend-stage docker.flows.sh/app-frontend-stage:${{github.sha}}
      - run: docker stop flows-web-frontend-stage
      - run: docker rm flows-web-frontend-stage
      - run: docker run -d --restart always -p 6002:3000 --name flows-web-frontend-stage docker.flows.sh/web-frontend-stage:${{github.sha}}
      - run: docker stop flows-docs-frontend-stage
      - run: docker rm flows-docs-frontend-stage
      - run: docker run -d --restart always -p 6003:3000 --name flows-docs-frontend-stage docker.flows.sh/docs-frontend-stage:${{github.sha}}
      - run: docker stop flows-backend-stage
      - run: docker rm flows-backend-stage
      - run: docker run -d --restart always -p 6005:3000 --name flows-backend-stage docker.flows.sh/backend-stage:${{github.sha}}
